destination: ./build

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
    values:
      title: PHPZlc & Symfony4+
      description_auto: 1
      description: "为开发者提供全套Symfony实践教程和解决方案"
      tags: phpzlc,symfony,symfony4,web开发,php,实战教程,解决方案,知了虫,php开源,php框架
      author_no: 1
      img_all: 1

  - scope:
      path: "_posts/doc" # 一个空的字符串代表项目中所有的文件
    values:
      # column_title: 文档支持
      column_title: 实践教程
      layout: doc
      categories: post doc

  - scope:
      path: "_posts/blog" # 一个空的字符串代表项目中所有的文件
    values:
      column_title: 博客动态
      layout: blog
      categories: post blog
