destination: ./build

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

giteement:
  enable: true
  redirect_uri: https://phpzlc.com
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: phpzlc
  repo: phpzlc
  ClientID: 7135f2309c1bf78313cf2345df5edc2fa6f20dbfe8a2ad728981958736c12fa3
  ClientSecret: 2c0f1168d11e9eb18c78d796afe3267d0cb38d9254669de2ced30840246a08d6

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
    values:
      description_auto: 1
      description: "在Symfony4的基础上,提供成熟的Web应用程序开发教程和业务组件。"
      tags: phpzlc,symfony,symfony4,web开发,后端,php
      author_no: 1
      img_all: 1

  - scope:
      path: "_posts/doc" # 一个空的字符串代表项目中所有的文件
    values:
      column_title: 文档支持
      layout: doc
      categories: post doc

  - scope:
      path: "_posts/blog" # 一个空的字符串代表项目中所有的文件
    values:
      column_title: 博客动态
      layout: blog
      categories: post blog
