plugins: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
    values:
      title: "PHPZlc & Symfony4+"
      description: "在Symfony4的基础上,提供成熟的Web应用程序开发教程和业务组件。"
      tags: phpzlc,网站, symfony,symfony5,symfony4,web,网站,后端,php后端
      author_no: 1

  - scope:
      path: "_posts/doc" # 一个空的字符串代表项目中所有的文件
    values:
      column_title: 文档支持
      layout: doc
      categories: post doc

  - scope:
      path: "_posts/blog" # 一个空的字符串代表项目中所有的文件
    values:
      column_title: 博客动态
      layout: blog
      categories: post blog
