name: AuthBusiness
title: 登录授权(auth-business)
description: 提供登录,修改密码等基础功能
keys: auth,auth-business,phpzlc/auth-business,登录,授权
type: 业务组件
language:
version: v2.0
status: support
sort: 0
links:
  -
    title: gitee
    url: https://gitee.com/phpzlc/auth-business
  -
    title: github
    url: https://github.com/phpzlc/auth-business
  -
    title: composer
    url: https://packagist.org/packages/phpzlc/auth-business
menus:
  -
    title: AuthBusiness
