name: Admin
title: 后台内核(Admin)
description: 后台内核,为后台业务提供底层策略,写法支持.(导航菜单,基础页面)
keys: admin,phpzlc/admin,后台
type: 功能组件
language:
version: v2.0
status: support
sort: 0
links:
  -
    title: gitee
    url: https://gitee.com/phpzlc/admin
  -
    title: github
    url: https://github.com/phpzlc/admin
  -
    title: composer
    url: https://packagist.org/packages/phpzlc/admin
menus:
  -
    title: Admin
