name: gh-page-sync

on:
  push:
    branches:
      - master

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:phpzlc/phpzlc-doc.git"
          destination-repo: "git@gitee.com:phpzlc/phpzlc-doc.git"
  git-pages-construct:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - uses: yanglbme/gitee-pages-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 1044295598@qq.com
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: phpzlc/phpzlc
  slack-notification:
    runs-on: ubuntu-latest
    needs: [git-pages-construct, git-mirror]
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: gh-page-sync
          SLACK_MESSAGE: 官网线上部署成功
          SLACK_USERNAME: phpzlc.com
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}