name: gitee-sync

on: [ push, delete, create ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:phpzlc/phpzlc.github.io.git"
          destination-repo: "git@gitee.com:phpzlc/phpzlc.git"
  git-pages-construct:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/gitee-pages-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: hejunjie@zmit.cn
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: phpzlc/phpzlc