name: initialization-gitalk

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run script
        run: |
          pip install -r bin/init-gitalk/requirements.txt
          python bin/init-gitalk/init-gitalk.py ${{ secrets.SITE_URL }} ${{ secrets.SITEMAP_URL }} ${{ secrets.COMMENT_TOKEN }} ${{ secrets.USER_NAME }} ${{ secrets.COMMENT_REPO_NAME }}